sold/core/urls.py
from django.urls import path
from .views import index, contact, terms, about

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('terms/', terms, name='terms'),
    path('about/', about, name='about'),
]

sold/item/urls.py
from django.urls import path

from .views import detail, new_item, delete, edit, items, category_list

app_name = 'item'

urlpatterns = [
    path('search', items, name='items'),
    path('items/<int:pk>/', detail, name='detail'),
    path('items/<int:pk>/delete/', delete, name='delete'),
    path('items/<int:pk>/edit/', edit, name='edit'),
    path('new/', new_item, name='new_item'),
    path('category/<slug:category_slug>/', category_list, name='category_list'),
]

sold/sold/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import CreateView

from core.forms import SignupForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('item.urls')),
    path('', include('dashboard.urls')),
    path('', include('communication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration_urlpatterns = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=SignupForm,
            success_url=reverse_lazy('core:index'),
        ),
        name='registration',
    ),
]

urlpatterns += registration_urlpatterns

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

sold/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your E-mail address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


# class LoginForm(AuthenticationForm):
#     username = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Your username',
#         'class': 'w-full py-4 px-6 rounded-xl'
#     }))
#
#     password = forms.CharField(widget=forms.PasswordInput(attrs={
#         'placeholder': 'Your password',
#         'class': 'w-full py-4 px-6 rounded-xl'
#     }))# class LoginForm(AuthenticationForm):
# #     username = forms.CharField(widget=forms.TextInput(attrs={
# #         'placeholder': 'Your username',
# #         'class': 'w-full py-4 px-6 rounded-xl'
# #     }))
# #
# #     password = forms.CharField(widget=forms.PasswordInput(attrs={
# #         'placeholder': 'Your password',
# #         'class': 'w-full py-4 px-6 rounded-xl'
# #     }))

sold/core/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

from item.models import Category, Item


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('?')

    paginator = Paginator(items, 3)

    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    template = 'core/index.html'
    categories = Category.objects.all()
    context = {
        'items': items,
        'categories': categories
    }
    return render(request, template, context)


def contact(request):
    template = 'static/contact.html'
    return render(request, template)


def about(request):
    template = 'static/about.html'
    return render(request, template)


def terms(request):
    template = 'static/terms.html'
    return render(request, template)

# def signup(request):
#     template = 'core/signup.html'
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/login/')
#     else:
#         form = SignupForm()
#     context = {
#         'form': form
#     }
#     return render(request, template, context)

sold/templates/core/contact.html
{% extends 'base.html' %}

{% block title %}Contact page{% endblock %}

{% block content %}
    <h1> The contact page </h1>
{% endblock %}

sold/templates/core/index.html
{% extends 'base.html' %}

{% block title %}Home page{% endblock %}

{% block mainpic %}
<section class="w-full mx-auto bg-nordic-gray-light flex pt-12 md:pt-0 md:items-center bg-cover bg-right rounded-xl" style="max-width:1600px; height: 32rem; background-image: url('https://images.unsplash.com/photo-1422190441165-ec2956dc9ecc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1600&q=80');">
	<div class="container mx-auto">
		<div class="flex flex-col w-full lg:w-1/2 justify-center items-start  px-6 tracking-wide">
			<h1 class="text-black text-2xl my-4">Start creating. Start earning.</h1>
			<a class="text-xl inline-block no-underline border-b border-gray-600 leading-relaxed hover:text-black hover:border-black" href="#">Explore more</a>
		</div>
	  </div>
</section>
{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="font-semibold mb-12 text-2xl text-center">Latest Arrivals</h2>
      <div  class="grid grid-cols-3 grap-3">


          {% for item in items %}
            <div class="ml-4 mr-4 mb-4">
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl" alt="this is alt parametr" >
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2-xl">
                            {{ item.name }}
                        </h2>
                        <p class="text-gray-500">
                            Price: {{ item.price }}
                        </p>
                    </div>
                </a>
            </div>
          {% endfor %}
      </div>



    <div class="pagination mt-6" style="display: flex; justify-content: center;">
    <span class="step-links">
        {% if items.has_previous %}
            <a class="pagination-link px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" href="?page=1">&laquo; Первая</a>
            <a class="pagination-link px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" href="?page={{ items.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="px-6 current-page">
            Страница {{ items.number }} из {{ items.paginator.num_pages }}.
        </span>

        {% if items.has_next %}
            <a class="pagination-link px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" href="?page={{ items.next_page_number }}">Следующая</a>
            <a class="pagination-link px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" href="?page={{ items.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>



    </div>






    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
      <div  class="grid grid-cols-3 grap-3">

        {% for category in categories %}
        <div>
            <a href="{% url 'item:category_list' category.slug %}">

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2-xl">
                        {{ category.name }}
                    </h2>
                    <p class="text-gray-500">
                        {{ category.items.count }} items
                    </p>
                </div>
            </a>
        </div>

        {% endfor %}
      </div>
    </div>
{% endblock %}

sold/templates/core/login.html
{% extends 'base.html' %}

{% block title %}
SignUp
{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
      <h1 class="mb-6 text-3xl">Log in</h1>

      <form method="post" action=".">
          {% csrf_token %}
          {{ form.non_field_errors }}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div><br>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

          <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
      </form>
      <div>
        <a href="{% url 'password_reset' %}">Забыли пароль?</a>
      </div>
    </div>
{% endblock %}

sold/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}
SignUp
{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
      <h1 class="mb-6 text-3xl">Sign Up</h1>

      <form method="post" action=".">
          {% csrf_token %}
          {{ form.non_field_errors }}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">E-mail</label><br>
                {{ form.email }}
            </div>

            <div class="mb-">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div><br>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>
            {% endif %}

          <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
      </form>
    </div>
{% endblock %}