sold/communication/urls.py
from django.urls import path
from .views import new_communication, inbox, detail

app_name = 'communication'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox/<int:pk>/', detail, name='detail'),
    path('inbox/new/<int:item_pk>/', new_communication, name='new_communication'),
]

sold/core/urls.py
from django.urls import path
from .views import index, contact, terms, about

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('terms/', terms, name='terms'),
    path('about/', about, name='about'),
]

sold/item/urls.py
from django.urls import path

from .views import detail, new_item, delete, edit, items, category_list

app_name = 'item'

urlpatterns = [
    path('search', items, name='items'),
    path('items/<int:pk>/', detail, name='detail'),
    path('items/<int:pk>/delete/', delete, name='delete'),
    path('items/<int:pk>/edit/', edit, name='edit'),
    path('new/', new_item, name='new_item'),
    path('category/<slug:category_slug>/', category_list, name='category_list'),
]

sold/sold/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import CreateView

from core.forms import SignupForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('item.urls')),
    path('', include('dashboard.urls')),
    path('', include('communication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration_urlpatterns = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=SignupForm,
            success_url=reverse_lazy('core:index'),
        ),
        name='registration',
    ),
]

urlpatterns += registration_urlpatterns

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

sold/item/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_resized import ResizedImageField

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField('Slug', max_length=64, blank=True, null=True, default=None)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'
        verbose_name = 'category'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = ResizedImageField('Картинка', upload_to='images', size=[600, 600], crop=['middle', 'center'], blank=True,
                              null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

sold/item/forms.py
from django import forms

from .models import Item

INPUT_FORMATS = 'w-full py-4 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_FORMATS
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_FORMATS
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_FORMATS
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_FORMATS
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_FORMATS
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_FORMATS
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_FORMATS
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_FORMATS
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_FORMATS
            })
        }

sold/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from item.forms import NewItemForm, EditItemForm
from item.models import Item, Category


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    template = 'item/items.html'

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))  # Выполняет поиск по имени

    context = {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    }
    return render(request, template, context)


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    template = 'item/detail.html'
    context = {
        'item': item,
        'related_items': related_items
    }
    return render(request, template, context)


@login_required
def new_item(request):
    template = 'item/new_item.html'
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.pk)
    else:
        form = NewItemForm()

    context = {'form': form,
               'title': 'New Item'}

    return render(request, template, context)


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    template = 'item/new_item.html'
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    context = {
        'form': form,
        'title': 'Edit item',
    }

    return render(request, template, context)


def category_list(request, category_slug):
    template = 'Item/category_list.html'
    item_by_category = Item.objects.filter(category__slug=category_slug)
    context = {
        'item_by_category': item_by_category,
    }
    return render(request, template, context)

sold/templates/item/category_list.html
{% extends 'base.html' %}

{% block title %}
    Категории листинг
{% endblock %}

{% block content %}

    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-12 px-0">

            {% for category in item_by_category %}
                <div class="ml-4 mr-4 mb-4">
                    <a href="{% url 'item:detail' category.id %}">
                        <div>
                            <img src="{{ category.image.url }}" class="rounded-t-xl" alt="this is alt parametr">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2-xl">
                                {{ category.name }}
                            </h2>
                            <p class="text-gray-500">
                                Price: {{ category.price }}
                            </p>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

sold/templates/item/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ item.name }}
{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" alt="this is alt parametr" class="rounded-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>

            {% if item.description %}

                <p class="text-gray-700">
                    <strong class="text-gray-500">Description: </strong><br>
                    {{ item.description }}
                </p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!</p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'communication:new_communication' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>
          <div  class="grid grid-cols-3 grap-3">
              {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" alt="this is alt parametr">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2-xl">
                                {{ item.name }}
                            </h2>
                            <p class="text-gray-500">
                                Price: {{ item.price }}
                            </p>
                        </div>
                    </a>
                </div>
              {% endfor %}
          </div>
    </div>
{% endblock %}

sold/templates/item/items.html
{% extends 'base.html' %}

{% block title %}
    Items
{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
      <div class="px-3 py-3 col-span-1">
          <form method="get" action="{% url 'item:items' %}">
              <input name="query" class="w-full py-4 px-4 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, chair or a car">
              <button class="mt-2 py-4 px-4 text-lg bg-teal-500 text-white rounded-xl">Search</button>
          </form>

          <hr class="my-6">
          <p class="py-3 font-semibold">Or just choose a category:</p>

          {% for category in categories %}
              <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
              </li>
          {% endfor %}

          <hr class="my-6">
          <p class="font-semibold">Clear filters</p>

          <ul>
              <li>
                  <a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
              </li>
          </ul>

      </div>
      <div class="col-span-3">
        <div class="py-3 px-3 grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

sold/templates/item/new_item.html
{% extends 'base.html' %}

{% block title %}
{{ titile }}
{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>
    <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
        <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
{% endblock %}