sold/communication/urls.py
from django.urls import path
from .views import new_communication, inbox, detail

app_name = 'communication'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox/<int:pk>/', detail, name='detail'),
    path('inbox/new/<int:item_pk>/', new_communication, name='new_communication'),
]

sold/core/urls.py
from django.urls import path
from .views import index, contact, terms, about

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('terms/', terms, name='terms'),
    path('about/', about, name='about'),
]

sold/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard', views.index, name='index'),
]

sold/item/urls.py
from django.urls import path

from .views import detail, new_item, delete, edit, items, category_list

app_name = 'item'

urlpatterns = [
    path('search', items, name='items'),
    path('items/<int:pk>/', detail, name='detail'),
    path('items/<int:pk>/delete/', delete, name='delete'),
    path('items/<int:pk>/edit/', edit, name='edit'),
    path('new/', new_item, name='new_item'),
    path('category/<slug:category_slug>/', category_list, name='category_list'),
]

sold/sold/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import CreateView

from core.forms import SignupForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('item.urls')),
    path('', include('dashboard.urls')),
    path('', include('communication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration_urlpatterns = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=SignupForm,
            success_url=reverse_lazy('core:index'),
        ),
        name='registration',
    ),
]

urlpatterns += registration_urlpatterns

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

sold/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:200,400&display=swap" rel="stylesheet">


    <title>{% block title %}{% endblock %}</title>
</head>

<body class="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal">

<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
    <a href="/"
       class="italic flex items-center tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl ">S
        O L D</a>
    <div class="space-x-6">
        <a href="{% url 'item:new_item' %}"
           class="inline-block no-underline hover:text-black hover:underline py-2 px-4">Add product</a>
        <a href="{% url 'item:items' %}" class="inline-block no-underline hover:text-black hover:underline py-2 px-4">Searching</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'communication:inbox' %}"
               class="px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Chat</a>
            <a href="{% url 'dashboard:index' %}"
               class="px-6 py-3 text lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My
                products</a>
            <a href="{% url 'logout' %}"
               class="px-6 py-3 text lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Logout</a>
        {% else %}
            <a href="{% url 'registration' %}"
               class="px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
            <a href="{% url 'login' %}"
               class="px-6 py-3 text lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log in</a>
        {% endif %}
    </div>
</nav>

{% block mainpic %}
{% endblock %}

<div class="px-6 py-6">
    {% block content %}
    {% endblock %}
</div>

<footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-500">About</h3>
        <p class="text-lg text-gray-500">Here you can find customers on your goods if you are a seller. <br>
            Or if you are a buyer - you can find any goods with good price.
        </p>
    </div>

    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
            <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
            <li><a href="{% url 'core:terms' %}" class="text-lg text-teal-500 hover:text-teal-700">Terms and
                conditions</a></li>
        </ul>
    </div>
</footer>
</body>
</html>